_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.13
            "5": 0.19.9
            "6": 4.30.0
            "8":
                - 1
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 4
dataset:
    value: 2.Первый жанр без клауз, включающих наречия
device:
    value: cuda
epochs:
    value: 2
freq:
    value: null
learning_rate:
    value: 1e-05
max_length:
    value: 512
model:
    value: gpt2
model_name:
    value: gpt2
model_type:
    value: gpt
num_repeats:
    value: 6
test_size:
    value: 0.2
threshold:
    value: 0.5
tokenizer:
    value: 'GPT2TokenizerFast(name_or_path=''gpt2'', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side=''right'', truncation_side=''right'', special_tokens={''bos_token'': ''<|endoftext|>'', ''eos_token'': ''<|endoftext|>'', ''unk_token'': ''<|endoftext|>''}, clean_up_tokenization_spaces=True)'
type:
    value: pos
