_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.13
            "5": 0.19.9
            "6": 4.30.0
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": linux-x86_64
